-- 095_a_viewing_is_a_dated_event.sql
-- A viewing becomes a dated event. Rewatches become entries, not a counter.
--
-- ── What is wrong today ────────────────────────────────────────────────────
-- `watched_items` is UNIQUE (user_id, item_id, item_type): one row per title
-- per person, with one `watched_at`. `user_media_status.watch_count` was meant
-- to hold the rest and has never been written by anything that survived —
-- `record_rewatch()` was its only writer and 091 dropped it as "written, never
-- called". So the diary is a set, not a log. You cannot say you saw a film at
-- the cinema in 2019 and again on the couch last night; the profile page
-- removed its "Film Diary" section for exactly this reason (see the comment
-- at src/app/app/profile/[id]/page.tsx around the Films section).
--
-- Every retention mechanic with evidence behind it — on this day, a calendar,
-- a year that leads with people and moments, rewatching as a first-class act —
-- needs the viewing to be a row with a date. docs/WHY_PEOPLE_COME_BACK.md §3.1
-- and §9 Bet 1 carry the argument; this file carries the schema.
--
-- ── The shape ──────────────────────────────────────────────────────────────
-- One row per time somebody watched something. The date is a DATE, not a
-- timestamp: people remember "the Friday we watched it", never the minute,
-- and a date survives timezones without an argument. `rewatch` is stored
-- rather than derived so the *first* row stays the first row when an older
-- viewing is logged later. `place` and `provider_id` are the two facts about
-- a viewing that people actually recall and that make a memory re-readable.
--
-- ── Additive, with projections ─────────────────────────────────────────────
-- Nothing is dropped and no reader changes in this migration. Following 065's
-- pattern, the legacy columns become a *projection* of the new table, kept
-- alive by trigger: `watched_items.watched_at` is the most recent viewing and
-- `user_media_status.watch_count` is the number of them. Every reader of those
-- columns keeps working; new readers use `viewings` directly.
--
-- The backfill creates exactly one viewing per title that is currently
-- `watched`, dated from `watched_items.watched_at` (the honest date for both
-- imports and in-app marks — see yearInReview.ts), falling back to the status
-- row's `updated_at`. It runs BEFORE the projection triggers are attached, so
-- it cannot rewrite the timestamps it was derived from.
--
-- `get_user_stats.watched_this_year` moves onto this table. It used to read
-- `user_media_status.updated_at`, which any status edit touches — so
-- changing a poster last week counted a 2019 film as watched this year.
--
-- Idempotent. Refuses to finish if the backfill left a watched title with no
-- viewing.

BEGIN;

CREATE TABLE IF NOT EXISTS public.viewings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    item_id text NOT NULL,
    item_type text NOT NULL,
    watched_on date NOT NULL DEFAULT CURRENT_DATE,
    rewatch boolean NOT NULL DEFAULT false,
    place text NOT NULL DEFAULT 'home',
    provider_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT viewings_item_type_check CHECK (item_type IN ('movie', 'tv')),
    CONSTRAINT viewings_place_check CHECK (place IN ('home', 'cinema', 'other'))
);

CREATE INDEX IF NOT EXISTS viewings_user_date_idx ON public.viewings USING btree (user_id, watched_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS viewings_user_item_idx ON public.viewings USING btree (user_id, item_id, item_type);
CREATE INDEX IF NOT EXISTS viewings_item_idx ON public.viewings USING btree (item_id, item_type);

ALTER TABLE public.viewings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS viewings_self ON public.viewings;
CREATE POLICY viewings_self ON public.viewings
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- The same predicate the rest of the library uses (081), so a viewing is
-- exactly as visible as the watched row it dates.
DROP POLICY IF EXISTS viewings_select_profile_visible ON public.viewings;
CREATE POLICY viewings_select_profile_visible ON public.viewings
  FOR SELECT USING (auth.uid() = user_id OR public.profile_visible_to_viewer(user_id));

-- The default ACL grants anon ALL on a new table; a signed-out visitor reads
-- the diary and never writes it.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.viewings FROM anon;
GRANT SELECT ON TABLE public.viewings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.viewings TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.viewings_id_seq TO authenticated, service_role;

-- ── Backfill: one viewing per watched title ────────────────────────────────
INSERT INTO public.viewings (user_id, item_id, item_type, watched_on, rewatch, created_at)
SELECT s.user_id,
       s.item_id,
       s.item_type,
       (COALESCE(w.watched_at, s.updated_at) AT TIME ZONE 'UTC')::date,
       false,
       COALESCE(w.watched_at, s.updated_at)
  FROM public.user_media_status s
  LEFT JOIN public.watched_items w
    ON w.user_id = s.user_id AND w.item_id = s.item_id AND w.item_type = s.item_type
 WHERE s.status = 'watched'
   AND NOT EXISTS (
     SELECT 1 FROM public.viewings v
      WHERE v.user_id = s.user_id AND v.item_id = s.item_id AND v.item_type = s.item_type
   );

-- ── Projections ────────────────────────────────────────────────────────────
-- Statement triggers with transition tables, as 069 argued: an import inserts
-- viewings in chunks, and one recount per affected title beats one per row.
-- Joined to `users` (093's lesson) so an account-delete cascade, which fires
-- this after the user row is gone, does not abort the delete.
CREATE OR REPLACE FUNCTION public.project_viewings() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT DISTINCT a.user_id, a.item_id, a.item_type
      FROM affected a
      JOIN public.users u ON u.id = a.user_id
  LOOP
    UPDATE public.watched_items w
       SET watched_at = COALESCE(
             (SELECT (max(v.watched_on))::timestamp with time zone
                FROM public.viewings v
               WHERE v.user_id = r.user_id AND v.item_id = r.item_id AND v.item_type = r.item_type),
             w.watched_at)
     WHERE w.user_id = r.user_id AND w.item_id = r.item_id AND w.item_type = r.item_type;

    UPDATE public.user_media_status s
       SET watch_count = GREATEST(1, (
             SELECT count(*)::integer
               FROM public.viewings v
              WHERE v.user_id = r.user_id AND v.item_id = r.item_id AND v.item_type = r.item_type))
     WHERE s.user_id = r.user_id AND s.item_id = r.item_id AND s.item_type = r.item_type;
  END LOOP;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS project_viewings_ins ON public.viewings;
CREATE TRIGGER project_viewings_ins AFTER INSERT ON public.viewings
  REFERENCING NEW TABLE AS affected FOR EACH STATEMENT EXECUTE FUNCTION public.project_viewings();
DROP TRIGGER IF EXISTS project_viewings_del ON public.viewings;
CREATE TRIGGER project_viewings_del AFTER DELETE ON public.viewings
  REFERENCING OLD TABLE AS affected FOR EACH STATEMENT EXECUTE FUNCTION public.project_viewings();
DROP TRIGGER IF EXISTS project_viewings_upd ON public.viewings;
CREATE TRIGGER project_viewings_upd AFTER UPDATE ON public.viewings
  REFERENCING NEW TABLE AS affected FOR EACH STATEMENT EXECUTE FUNCTION public.project_viewings();

-- ── The one way a "watched" becomes a viewing ──────────────────────────────
-- Every writer that marks a title watched — the status route, quick-add,
-- finishing a series, favouriting, an import with no dates — calls this
-- instead of re-implementing "insert a viewing dated today if none exists".
-- One round trip for a whole batch; pinned to auth.uid(), so it can only
-- ever write the caller's own diary. Companions are never inferred here: a
-- one-tap "Watched" says nothing about who was there, and the room from a
-- Tonight session is a *suggestion* the logger confirms in the log panel.
CREATE OR REPLACE FUNCTION public.ensure_first_viewings(p_items jsonb) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_me uuid := auth.uid();
  v_n integer := 0;
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'You have to be signed in.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  WITH wanted AS (
    SELECT DISTINCT i->>'item_id' AS item_id, i->>'item_type' AS item_type
      FROM jsonb_array_elements(COALESCE(p_items, '[]'::jsonb)) AS i
     WHERE i->>'item_type' IN ('movie', 'tv')
       AND COALESCE(i->>'item_id', '') <> ''
  ), inserted AS (
    INSERT INTO public.viewings (user_id, item_id, item_type, watched_on, rewatch)
    SELECT v_me, w.item_id, w.item_type, CURRENT_DATE, false
      FROM wanted w
     WHERE NOT EXISTS (
       SELECT 1 FROM public.viewings v
        WHERE v.user_id = v_me AND v.item_id = w.item_id AND v.item_type = w.item_type)
    RETURNING 1
  )
  SELECT count(*) INTO v_n FROM inserted;
  RETURN v_n;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.ensure_first_viewings(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ensure_first_viewings(jsonb) TO authenticated, service_role;

-- ── The stats figure that was counting the wrong thing ─────────────────────
CREATE OR REPLACE FUNCTION public.get_user_stats(p_user_id uuid)
RETURNS TABLE(watched_count integer, movie_count integer, tv_count integer,
              watchlist_count integer, watching_count integer, favorite_count integer,
              episodes_count integer, watched_this_year integer)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
  with live as (
    select
      count(*) filter (where status = 'watched')::int                          as watched_count,
      count(*) filter (where status = 'watched' and item_type = 'movie')::int  as movie_count,
      count(*) filter (where status = 'watched' and item_type = 'tv')::int     as tv_count,
      count(*) filter (where status = 'watchlist')::int                        as watchlist_count,
      count(*) filter (where status = 'watching')::int                         as watching_count
    from public.user_media_status
    where user_id = p_user_id
  )
  select live.watched_count, live.movie_count, live.tv_count,
         live.watchlist_count, live.watching_count,
         coalesce((select count(*)::int from public.favorite_items where user_id = p_user_id), 0),
         coalesce(cs.episodes_count, 0),
         coalesce((select count(distinct (v.item_id, v.item_type))::int
                     from public.viewings v
                    where v.user_id = p_user_id
                      and v.watched_on >= date_trunc('year', now())::date), 0)
  from live
  left join public.user_cout_stats cs on cs.user_id = p_user_id;
$$;

-- ── Verify ─────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_missing integer;
  v_policies integer;
BEGIN
  SELECT count(*) INTO v_missing
    FROM public.user_media_status s
   WHERE s.status = 'watched'
     AND NOT EXISTS (
       SELECT 1 FROM public.viewings v
        WHERE v.user_id = s.user_id AND v.item_id = s.item_id AND v.item_type = s.item_type);
  IF v_missing > 0 THEN
    RAISE EXCEPTION '% watched titles have no viewing after the backfill', v_missing;
  END IF;

  SELECT count(*) INTO v_policies FROM pg_policies
   WHERE schemaname = 'public' AND tablename = 'viewings';
  IF v_policies <> 2 THEN
    RAISE EXCEPTION 'viewings should carry 2 policies, has %', v_policies;
  END IF;
  IF has_function_privilege('anon', 'public.ensure_first_viewings(jsonb)', 'EXECUTE') THEN
    RAISE EXCEPTION 'anon can execute ensure_first_viewings';
  END IF;

  RAISE NOTICE 'verified: every watched title has a viewing; % rows in viewings',
    (SELECT count(*) FROM public.viewings);
END $$;

COMMIT;
