-- 096_a_viewing_knows_who_was_there.sql
-- "Watched with" becomes a fact on the viewing, and a fact the other person
-- can answer.
--
-- ── Why this is the field ──────────────────────────────────────────────────
-- Shared media use predicts closeness in couples, most strongly for couples
-- who lack shared friends (Gomillion et al. 2017); the social-bonding function
-- of memory is as strong as the self function (Bluck & Alea 2011); and no
-- tracker on the market records *who* — Trakt's answer to households is "use
-- separate devices". The composer already asks "Who did you watch it with?"
-- as free text nobody can link to. docs/WHY_PEOPLE_COME_BACK.md §3.6, §9 Bet 2.
--
-- ── The shape ──────────────────────────────────────────────────────────────
-- A companion is either a person on letsee (`companion_user_id`) or a plain
-- name for someone who is not (`name`). Exactly one of the two is set. A
-- viewing may name many companions; the same person is named at most once.
--
-- `linked_viewing_id` is what makes it reciprocal. When a companion who is on
-- letsee taps "I was there too", `accept_co_log` creates *their own* viewing,
-- links the two rows in both directions, and marks the title watched in their
-- library. Nobody's library is ever written by somebody else's tap: the
-- original row names them, and the row in their diary exists only once they
-- accept. That is the same rule Tonight's decide route already states —
-- "only the caller's own status is written".
--
-- ── The notification ───────────────────────────────────────────────────────
-- `co_log_invite` is a person addressing a person, on purpose, about
-- something you would want to answer — which is the definition 092 applied
-- when it cut the list to four. 096, 097 and 098 each rewrite the CHECK to the
-- same full list of nine, so whichever of them runs last leaves the same
-- constraint and no trigger ever inserts a kind the CHECK refuses. Blocked
-- pairs are never notified.
--
-- Idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS public.viewing_companions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewing_id bigint NOT NULL REFERENCES public.viewings(id) ON DELETE CASCADE,
    companion_user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    name text,
    linked_viewing_id bigint REFERENCES public.viewings(id) ON DELETE SET NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT viewing_companions_someone_check
      CHECK (companion_user_id IS NOT NULL OR NULLIF(btrim(name), '') IS NOT NULL)
);

-- The same person once per viewing, whether they are a user or a name.
CREATE UNIQUE INDEX IF NOT EXISTS viewing_companions_identity_idx
  ON public.viewing_companions (viewing_id, COALESCE(companion_user_id::text, lower(btrim(name))));
CREATE INDEX IF NOT EXISTS viewing_companions_companion_idx
  ON public.viewing_companions USING btree (companion_user_id);
CREATE INDEX IF NOT EXISTS viewing_companions_viewing_idx
  ON public.viewing_companions USING btree (viewing_id);

ALTER TABLE public.viewing_companions ENABLE ROW LEVEL SECURITY;

-- The owner of the viewing manages its companions.
DROP POLICY IF EXISTS viewing_companions_owner_all ON public.viewing_companions;
CREATE POLICY viewing_companions_owner_all ON public.viewing_companions
  USING (EXISTS (SELECT 1 FROM public.viewings v WHERE v.id = viewing_id AND v.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.viewings v WHERE v.id = viewing_id AND v.user_id = auth.uid()));

-- Anyone who may see the viewing may see who was there; and the person named
-- may always see that they were named, even on a private profile, because it
-- is a claim about them.
DROP POLICY IF EXISTS viewing_companions_select_visible ON public.viewing_companions;
CREATE POLICY viewing_companions_select_visible ON public.viewing_companions
  FOR SELECT USING (
    companion_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.viewings v
       WHERE v.id = viewing_id
         AND (v.user_id = auth.uid() OR public.profile_visible_to_viewer(v.user_id))
    )
  );

REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE public.viewing_companions FROM anon;
GRANT SELECT ON TABLE public.viewing_companions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.viewing_companions TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.viewing_companions_id_seq TO authenticated, service_role;

-- ── The notification type ──────────────────────────────────────────────────
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_notification_type_check;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_notification_type_check
  CHECK (notification_type = ANY (ARRAY[
    'follow_request'::text, 'follow_accepted'::text, 'new_follower'::text, 'dm_received'::text,
    'co_log_invite'::text, 'recommendation_watched'::text,
    'comment_reply'::text, 'watchlist_available'::text, 'new_episode'::text
  ]));

CREATE OR REPLACE FUNCTION public.notify_co_log_invite() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_owner uuid;
  v_item_id text;
  v_item_type text;
  v_watched_on date;
  v_name text;
  v_image text;
BEGIN
  IF NEW.companion_user_id IS NULL THEN RETURN NEW; END IF;
  -- A reciprocal row written by accept_co_log names somebody who already has
  -- their own viewing; there is nothing to invite them to.
  IF NEW.linked_viewing_id IS NOT NULL THEN RETURN NEW; END IF;

  SELECT v.user_id, v.item_id, v.item_type, v.watched_on
    INTO v_owner, v_item_id, v_item_type, v_watched_on
    FROM public.viewings v WHERE v.id = NEW.viewing_id;
  IF v_owner IS NULL OR v_owner = NEW.companion_user_id THEN RETURN NEW; END IF;
  IF public.is_blocked(v_owner, NEW.companion_user_id) THEN RETURN NEW; END IF;

  -- One invite per viewing per person, however many times the row is re-saved.
  IF EXISTS (
    SELECT 1 FROM public.notifications n
     WHERE n.user_id = NEW.companion_user_id
       AND n.notification_type = 'co_log_invite'
       AND n.target_type = 'viewing'
       AND n.target_id = NEW.viewing_id
  ) THEN RETURN NEW; END IF;

  SELECT s.item_name, s.image_url INTO v_name, v_image
    FROM public.user_media_status s
   WHERE s.user_id = v_owner AND s.item_id = v_item_id AND s.item_type = v_item_type;

  INSERT INTO public.notifications (user_id, notification_type, actor_id, target_type, target_id, metadata)
  VALUES (
    NEW.companion_user_id, 'co_log_invite', v_owner, 'viewing', NEW.viewing_id,
    jsonb_build_object(
      'item_id', v_item_id,
      'item_type', v_item_type,
      'item_name', COALESCE(v_name, ''),
      'image_url', v_image,
      'watched_on', v_watched_on
    )
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_co_log_invite ON public.viewing_companions;
CREATE TRIGGER trg_notify_co_log_invite AFTER INSERT ON public.viewing_companions
  FOR EACH ROW EXECUTE FUNCTION public.notify_co_log_invite();

-- ── "I was there too" ──────────────────────────────────────────────────────
-- Pinned to auth.uid(): the caller can only accept an invitation that names
-- them. Returns the id of the caller's own viewing (existing or new).
CREATE OR REPLACE FUNCTION public.accept_co_log(p_viewing_id bigint) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_me uuid := auth.uid();
  v_companion_id bigint;
  v_linked bigint;
  v_owner uuid;
  v_item_id text;
  v_item_type text;
  v_watched_on date;
  v_place text;
  v_provider integer;
  v_name text;
  v_image text;
  v_adult boolean;
  v_genres text[];
  v_new bigint;
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'You have to be signed in.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT c.id, c.linked_viewing_id, v.user_id, v.item_id, v.item_type, v.watched_on, v.place, v.provider_id
    INTO v_companion_id, v_linked, v_owner, v_item_id, v_item_type, v_watched_on, v_place, v_provider
    FROM public.viewing_companions c
    JOIN public.viewings v ON v.id = c.viewing_id
   WHERE c.viewing_id = p_viewing_id AND c.companion_user_id = v_me;

  IF v_companion_id IS NULL THEN
    RAISE EXCEPTION 'You were not named on that viewing.' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_linked IS NOT NULL THEN
    RETURN v_linked;
  END IF;
  IF public.is_blocked(v_me, v_owner) THEN
    RAISE EXCEPTION 'That viewing is not available.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT s.item_name, s.image_url, s.item_adult, s.genres
    INTO v_name, v_image, v_adult, v_genres
    FROM public.user_media_status s
   WHERE s.user_id = v_owner AND s.item_id = v_item_id AND s.item_type = v_item_type;

  -- My library. A series I am part-way through stays part-way through: a
  -- friend logging "we watched Severance" must not mark it complete for me.
  INSERT INTO public.user_media_status
    (user_id, item_id, item_type, item_name, image_url, item_adult, genres, status, updated_at)
  VALUES
    (v_me, v_item_id, v_item_type, COALESCE(v_name, ''), v_image, COALESCE(v_adult, false),
     COALESCE(v_genres, '{}'::text[]), 'watched', now())
  ON CONFLICT (user_id, item_id, item_type) DO UPDATE
    SET status = CASE
                   WHEN public.user_media_status.item_type = 'tv'
                    AND public.user_media_status.status IN ('watching', 'on_hold', 'dropped')
                   THEN public.user_media_status.status
                   ELSE 'watched'
                 END,
        updated_at = now();

  INSERT INTO public.watched_items
    (user_id, item_id, item_type, item_name, image_url, item_adult, genres, is_watched)
  VALUES
    (v_me, v_item_id, v_item_type, COALESCE(v_name, ''), v_image, COALESCE(v_adult, false),
     COALESCE(v_genres, '{}'::text[]), true)
  ON CONFLICT (user_id, item_id, item_type) DO UPDATE SET is_watched = true;

  INSERT INTO public.viewings (user_id, item_id, item_type, watched_on, rewatch, place, provider_id)
  VALUES (
    v_me, v_item_id, v_item_type, v_watched_on,
    EXISTS (SELECT 1 FROM public.viewings x
             WHERE x.user_id = v_me AND x.item_id = v_item_id AND x.item_type = v_item_type),
    v_place, v_provider
  )
  RETURNING id INTO v_new;

  -- Link both ways. The reciprocal row carries linked_viewing_id from birth,
  -- which is what stops notify_co_log_invite inviting the original logger.
  INSERT INTO public.viewing_companions (viewing_id, companion_user_id, linked_viewing_id)
  VALUES (v_new, v_owner, p_viewing_id)
  ON CONFLICT DO NOTHING;

  UPDATE public.viewing_companions SET linked_viewing_id = v_new WHERE id = v_companion_id;

  UPDATE public.notifications
     SET is_read = true
   WHERE user_id = v_me AND notification_type = 'co_log_invite'
     AND target_type = 'viewing' AND target_id = p_viewing_id;

  RETURN v_new;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.accept_co_log(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_co_log(bigint) TO authenticated, service_role;

-- ── Who somebody watches with ──────────────────────────────────────────────
-- Grouped by person, whether they are a user or a name. Guarded by the same
-- visibility predicate as the library, and blocked users are never listed to
-- the person who blocked them. Callable signed out, like the profile it sits on.
CREATE OR REPLACE FUNCTION public.watch_companions(p_user_id uuid, p_limit integer DEFAULT 6)
RETURNS TABLE(companion_user_id uuid, name text, username text, avatar_url text,
              viewings integer, last_watched_on date)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
  SELECT c.companion_user_id,
         min(c.name) AS name,
         u.username,
         u.avatar_url,
         count(*)::integer AS viewings,
         max(v.watched_on) AS last_watched_on
    FROM public.viewings v
    JOIN public.viewing_companions c ON c.viewing_id = v.id
    LEFT JOIN public.users u ON u.id = c.companion_user_id AND u.deleted_at IS NULL
   WHERE v.user_id = p_user_id
     AND public.profile_visible_to_viewer(p_user_id)
     AND (c.companion_user_id IS NULL OR u.id IS NOT NULL)
     AND (auth.uid() IS NULL OR c.companion_user_id IS NULL
          OR NOT public.is_blocked(auth.uid(), c.companion_user_id))
   GROUP BY c.companion_user_id, u.username, u.avatar_url,
            COALESCE(c.companion_user_id::text, lower(btrim(c.name)))
   ORDER BY count(*) DESC, max(v.watched_on) DESC
   LIMIT GREATEST(1, LEAST(p_limit, 24));
$$;

GRANT EXECUTE ON FUNCTION public.watch_companions(uuid, integer) TO anon, authenticated, service_role;

-- ── Who was in the room ────────────────────────────────────────────────────
-- The people from a Tonight session that decided on this title in the last
-- three days, if the caller was in it. This is how the diary becomes a
-- byproduct of the decision without anyone's library being written for them:
-- the companions are *suggested* at log time, and the logger confirms.
CREATE OR REPLACE FUNCTION public.room_companions(p_item_id text, p_item_type text)
RETURNS TABLE(user_id uuid, username text, avatar_url text)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
  SELECT DISTINCT ON (p.user_id) p.user_id, u.username, u.avatar_url
    FROM public.watch_sessions s
    JOIN public.watch_session_participants p ON p.session_id = s.id
    JOIN public.users u ON u.id = p.user_id AND u.deleted_at IS NULL
   WHERE auth.uid() IS NOT NULL
     AND s.decided_item_id = p_item_id
     AND s.decided_item_type = p_item_type
     AND s.decided_at >= now() - interval '3 days'
     AND p.user_id <> auth.uid()
     AND EXISTS (SELECT 1 FROM public.watch_session_participants me
                  WHERE me.session_id = s.id AND me.user_id = auth.uid())
     AND NOT public.is_blocked(auth.uid(), p.user_id)
   ORDER BY p.user_id, s.decided_at DESC;
$$;

REVOKE EXECUTE ON FUNCTION public.room_companions(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.room_companions(text, text) TO authenticated, service_role;

-- ── Verify ─────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_def text;
BEGIN
  SELECT pg_get_constraintdef(c.oid) INTO v_def
    FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid
   WHERE t.relname = 'notifications' AND c.conname = 'notifications_notification_type_check';
  IF v_def IS NULL OR v_def NOT LIKE '%co_log_invite%' THEN
    RAISE EXCEPTION 'co_log_invite is not an accepted notification type: %', v_def;
  END IF;
  IF to_regprocedure('public.accept_co_log(bigint)') IS NULL THEN
    RAISE EXCEPTION 'accept_co_log is missing';
  END IF;
  IF has_function_privilege('anon', 'public.accept_co_log(bigint)', 'EXECUTE') THEN
    RAISE EXCEPTION 'anon can execute accept_co_log';
  END IF;
  RAISE NOTICE 'verified: companions, co-log invites and accept_co_log in place';
END $$;

COMMIT;
