-- 097_a_save_has_a_why_a_when_and_a_who.sql
-- A watchlist entry carries the reason it was saved, the occasion it was
-- saved for, and the person it came from — and the person finds out when it
-- gets watched.
--
-- ── Why ────────────────────────────────────────────────────────────────────
-- A bare "watch later" is an intention with no plan. Forming an if-then plan
-- (when, where, with whom) raises follow-through by d ≈ 0.65 (Gollwitzer &
-- Sheeran 2006); pleasant experiences get procrastinated exactly like chores
-- unless they carry a deadline (Shu & Gneezy 2010); and recommending is
-- self-enhancing *and* bonding, which needs the recommender to find out
-- (Berger 2014). Letterboxd's users ask for precisely this — "add a note to a
-- movie I add to my watchlist! I often forget why I added them" — and no
-- tracker keeps a friend's recommendation as an object that can be closed.
-- docs/WHY_PEOPLE_COME_BACK.md §3.4, §5 gap 6, §9 Bet 3.
--
-- ── Two additions ──────────────────────────────────────────────────────────
-- 1. Columns on `user_media_status`, meaningful while status = 'watchlist':
--    `save_note` (why), `save_for` + `save_for_date` (when), `save_with_*`
--    (who), `saved_at`. They stay on the row after it is watched, because the
--    note is part of the memory ("Priya said it was like Columbo").
-- 2. `title_recommendations`: one row per (from, to, title). Written three
--    ways — by the recipient recording "Priya said" on a save, by the sender
--    sharing a title card in a message (trigger on `messages`), or explicitly.
--    Closed by the recipient's *viewing*: a trigger on `viewings` stamps
--    `watched_at` and sends the recommender exactly one `recommendation_watched`.
--
-- No fan-out: a recommendation notifies one person, once.
--
-- Idempotent.

BEGIN;

ALTER TABLE public.user_media_status
  ADD COLUMN IF NOT EXISTS save_note text,
  ADD COLUMN IF NOT EXISTS save_for text,
  ADD COLUMN IF NOT EXISTS save_for_date date,
  ADD COLUMN IF NOT EXISTS save_with_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS save_with_name text,
  ADD COLUMN IF NOT EXISTS saved_at timestamp with time zone;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_media_status_save_for_check') THEN
    ALTER TABLE public.user_media_status ADD CONSTRAINT user_media_status_save_for_check
      CHECK (save_for IS NULL OR save_for IN ('tonight', 'weekend', 'someday', 'date'));
  END IF;
END $$;

-- Anything already on a watchlist was saved when its row was last touched.
UPDATE public.user_media_status
   SET saved_at = updated_at
 WHERE status = 'watchlist' AND saved_at IS NULL;

-- ── Recommendations ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.title_recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    to_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    item_id text NOT NULL,
    item_type text NOT NULL,
    item_name text NOT NULL DEFAULT '',
    image_url text,
    note text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    watched_at timestamp with time zone,
    watched_viewing_id bigint REFERENCES public.viewings(id) ON DELETE SET NULL,
    dismissed_at timestamp with time zone,
    CONSTRAINT title_recommendations_item_type_check CHECK (item_type IN ('movie', 'tv')),
    CONSTRAINT title_recommendations_not_self_check CHECK (from_user_id <> to_user_id),
    CONSTRAINT title_recommendations_identity_key UNIQUE (from_user_id, to_user_id, item_id, item_type)
);

CREATE INDEX IF NOT EXISTS title_recommendations_to_idx
  ON public.title_recommendations USING btree (to_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS title_recommendations_from_idx
  ON public.title_recommendations USING btree (from_user_id, created_at DESC);

ALTER TABLE public.title_recommendations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS title_recommendations_select_party ON public.title_recommendations;
CREATE POLICY title_recommendations_select_party ON public.title_recommendations
  FOR SELECT USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

-- Either party may record one: the sender recommending, or the recipient
-- writing down who told them. Never across a block — and the recipient may
-- only name somebody they are connected to in either direction, because a
-- recommendation is later *closed* with a notification to its sender, and
-- naming a stranger would let anyone put words in anyone's mouth.
DROP POLICY IF EXISTS title_recommendations_insert_party ON public.title_recommendations;
CREATE POLICY title_recommendations_insert_party ON public.title_recommendations
  FOR INSERT WITH CHECK (
    NOT public.is_blocked(from_user_id, to_user_id)
    AND (
      auth.uid() = from_user_id
      OR (
        auth.uid() = to_user_id
        AND EXISTS (
          SELECT 1 FROM public.user_connections c
           WHERE (c.follower_id = to_user_id AND c.followed_id = from_user_id)
              OR (c.follower_id = from_user_id AND c.followed_id = to_user_id)
        )
      )
    )
  );

DROP POLICY IF EXISTS title_recommendations_update_recipient ON public.title_recommendations;
CREATE POLICY title_recommendations_update_recipient ON public.title_recommendations
  FOR UPDATE USING (auth.uid() = to_user_id) WITH CHECK (auth.uid() = to_user_id);

DROP POLICY IF EXISTS title_recommendations_delete_party ON public.title_recommendations;
CREATE POLICY title_recommendations_delete_party ON public.title_recommendations
  FOR DELETE USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

-- Recommendations are between two signed-in people; anon has no business here.
REVOKE ALL ON TABLE public.title_recommendations FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.title_recommendations TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.title_recommendations_id_seq TO authenticated, service_role;

-- ── The notification type ──────────────────────────────────────────────────
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_notification_type_check;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_notification_type_check
  CHECK (notification_type = ANY (ARRAY[
    'follow_request'::text, 'follow_accepted'::text, 'new_follower'::text, 'dm_received'::text,
    'co_log_invite'::text, 'recommendation_watched'::text,
    'comment_reply'::text, 'watchlist_available'::text, 'new_episode'::text
  ]));

-- ── A viewing closes the loop ──────────────────────────────────────────────
-- Fires on the recipient's viewing. Each open recommendation for that title
-- is stamped once and its sender told once; a rewatch a year later stamps
-- nothing, because nothing is open.
CREATE OR REPLACE FUNCTION public.close_recommendations_on_viewing() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  r record;
BEGIN
  FOR r IN
    UPDATE public.title_recommendations t
       SET watched_at = now(), watched_viewing_id = NEW.id
     WHERE t.to_user_id = NEW.user_id
       AND t.item_id = NEW.item_id
       AND t.item_type = NEW.item_type
       AND t.watched_at IS NULL
    RETURNING t.id, t.from_user_id, t.to_user_id, t.item_id, t.item_type, t.item_name, t.image_url
  LOOP
    IF NOT public.is_blocked(r.from_user_id, r.to_user_id) THEN
      INSERT INTO public.notifications (user_id, notification_type, actor_id, target_type, target_id, metadata)
      VALUES (
        r.from_user_id, 'recommendation_watched', r.to_user_id, 'recommendation', r.id,
        jsonb_build_object('item_id', r.item_id, 'item_type', r.item_type,
                           'item_name', r.item_name, 'image_url', r.image_url,
                           'watched_on', NEW.watched_on)
      );
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_close_recommendations ON public.viewings;
CREATE TRIGGER trg_close_recommendations AFTER INSERT ON public.viewings
  FOR EACH ROW EXECUTE FUNCTION public.close_recommendations_on_viewing();

-- ── A shared card is a recommendation ──────────────────────────────────────
-- `sendCard.tsx` inserts a `cardmix` message with the title in `metadata`.
-- That is somebody telling somebody to watch something, and it deserves to
-- land in the recipient's "from" lane rather than scroll away in a thread.
CREATE OR REPLACE FUNCTION public.record_card_recommendation() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_type text;
  v_id text;
BEGIN
  IF NEW.message_type::text <> 'cardmix' OR NEW.metadata IS NULL THEN RETURN NEW; END IF;
  v_type := NEW.metadata->>'media_type';
  v_id := NEW.metadata->>'media_id';
  IF v_id IS NULL OR v_type NOT IN ('movie', 'tv') THEN RETURN NEW; END IF;
  IF NEW.sender_id = NEW.recipient_id THEN RETURN NEW; END IF;

  INSERT INTO public.title_recommendations
    (from_user_id, to_user_id, item_id, item_type, item_name, image_url, note)
  VALUES
    (NEW.sender_id, NEW.recipient_id, v_id, v_type,
     COALESCE(NEW.metadata->>'media_name', ''), NEW.metadata->>'media_image',
     NULLIF(left(NEW.content, 280), ''))
  ON CONFLICT ON CONSTRAINT title_recommendations_identity_key DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_record_card_recommendation ON public.messages;
CREATE TRIGGER trg_record_card_recommendation AFTER INSERT ON public.messages
  FOR EACH ROW EXECUTE FUNCTION public.record_card_recommendation();

-- ── Verify ─────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_def text;
  v_cols integer;
BEGIN
  SELECT count(*) INTO v_cols
    FROM information_schema.columns
   WHERE table_schema = 'public' AND table_name = 'user_media_status'
     AND column_name IN ('save_note', 'save_for', 'save_for_date', 'save_with_user_id', 'save_with_name', 'saved_at');
  IF v_cols <> 6 THEN
    RAISE EXCEPTION 'user_media_status is missing save columns (% of 6 present)', v_cols;
  END IF;
  SELECT pg_get_constraintdef(c.oid) INTO v_def
    FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid
   WHERE t.relname = 'notifications' AND c.conname = 'notifications_notification_type_check';
  IF v_def NOT LIKE '%recommendation_watched%' OR v_def NOT LIKE '%co_log_invite%' THEN
    RAISE EXCEPTION 'notification types not widened: %', v_def;
  END IF;
  RAISE NOTICE 'verified: saves carry why/when/who; recommendations close on a viewing';
END $$;

COMMIT;
