-- 110_ask_your_people.sql
-- Ask your people for a film; they answer with a pass.
--
-- ── Why ────────────────────────────────────────────────────────────────────
-- "Something short and funny for tonight?" — asked of the people you watch
-- with, answered by them with a film each (docs/design/RETHINK.md §7, "Ask
-- your people": it replaces "recommended for you" as the way to find a film
-- when you don't know what you want).
--
-- ── Shape ──────────────────────────────────────────────────────────────────
-- `asks`: one question, open for three days unless you close it sooner.
-- An answer is an ordinary pass — a `cardmix` message, which 097's trigger
-- records in `title_recommendations` — tagged with the ask it answers, so it
-- shows in your room, in Up next from them, and under the question.
--
-- ── Who sees an ask ────────────────────────────────────────────────────────
-- You, and your people while it is open: anyone you follow or who follows
-- you, or anyone you have a room with (a message either way), never someone
-- either of you has blocked (`are_people`). Asking is limited to three a day;
-- answering to three films per ask.
--
-- Idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS public.asks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    question text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    closes_at timestamp with time zone NOT NULL DEFAULT (now() + interval '3 days'),
    closed_at timestamp with time zone,
    CONSTRAINT asks_question_check CHECK (length(btrim(question)) BETWEEN 3 AND 200)
);
CREATE INDEX IF NOT EXISTS asks_user_idx ON public.asks USING btree (user_id, created_at DESC);

ALTER TABLE public.title_recommendations ADD COLUMN IF NOT EXISTS ask_id bigint REFERENCES public.asks(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS title_recommendations_ask_idx ON public.title_recommendations USING btree (ask_id) WHERE ask_id IS NOT NULL;

-- Two people are each other's people: a follow either way, or a room.
CREATE OR REPLACE FUNCTION public.are_people(p_a uuid, p_b uuid)
RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
  SELECT p_a IS NOT NULL AND p_b IS NOT NULL AND p_a <> p_b
     AND NOT EXISTS (
       SELECT 1 FROM public.user_blocks b
        WHERE (b.blocker_id = p_a AND b.blocked_id = p_b) OR (b.blocker_id = p_b AND b.blocked_id = p_a)
     )
     AND (
       EXISTS (
         SELECT 1 FROM public.user_connections c
          WHERE (c.follower_id = p_a AND c.followed_id = p_b) OR (c.follower_id = p_b AND c.followed_id = p_a)
       )
       OR EXISTS (
         SELECT 1 FROM public.messages m
          WHERE (m.sender_id = p_a AND m.recipient_id = p_b) OR (m.sender_id = p_b AND m.recipient_id = p_a)
       )
     );
$$;
REVOKE ALL ON FUNCTION public.are_people(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.are_people(uuid, uuid) TO authenticated;

ALTER TABLE public.asks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS asks_select_own_or_people ON public.asks;
CREATE POLICY asks_select_own_or_people ON public.asks
  FOR SELECT USING (
    auth.uid() = user_id
    OR (closed_at IS NULL AND closes_at > now() AND public.are_people(auth.uid(), user_id))
  );

DROP POLICY IF EXISTS asks_update_own ON public.asks;
CREATE POLICY asks_update_own ON public.asks
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS asks_delete_own ON public.asks;
CREATE POLICY asks_delete_own ON public.asks
  FOR DELETE USING (auth.uid() = user_id);

REVOKE ALL ON TABLE public.asks FROM anon, authenticated;
GRANT SELECT, UPDATE (closed_at), DELETE ON TABLE public.asks TO authenticated;

-- ── Ask ────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.create_ask(p_question text)
RETURNS bigint
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_question text := regexp_replace(btrim(coalesce(p_question, '')), '\s+', ' ', 'g');
  v_id bigint;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'sign in to ask' USING ERRCODE = '42501';
  END IF;
  IF length(v_question) < 3 THEN
    RAISE EXCEPTION 'say a little more' USING ERRCODE = '22023';
  END IF;
  IF (SELECT count(*) FROM public.asks WHERE user_id = v_uid AND created_at > now() - interval '1 day') >= 3 THEN
    RAISE EXCEPTION 'three asks a day' USING ERRCODE = '54000';
  END IF;
  INSERT INTO public.asks (user_id, question) VALUES (v_uid, left(v_question, 200)) RETURNING id INTO v_id;
  RETURN v_id;
END $$;

-- ── Answer: a pass, tagged with the ask ────────────────────────────────────
CREATE OR REPLACE FUNCTION public.answer_ask(
  p_ask_id bigint,
  p_item_id text,
  p_item_type text,
  p_item_name text,
  p_image_url text,
  p_note text
)
RETURNS text
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER
    SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_ask public.asks%ROWTYPE;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'sign in to answer' USING ERRCODE = '42501';
  END IF;
  IF p_item_type NOT IN ('movie', 'tv') OR p_item_id !~ '^[0-9]{1,9}$' OR length(btrim(coalesce(p_item_name, ''))) = 0 THEN
    RAISE EXCEPTION 'pick a film or a series' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_ask FROM public.asks WHERE id = p_ask_id AND closed_at IS NULL AND closes_at > now();
  IF NOT FOUND OR v_ask.user_id = v_uid OR NOT public.are_people(v_uid, v_ask.user_id) THEN
    RETURN 'gone';
  END IF;
  IF (SELECT count(*) FROM public.title_recommendations WHERE ask_id = p_ask_id AND from_user_id = v_uid) >= 3 THEN
    RETURN 'enough';
  END IF;

  -- The same message a pass is; 097's trigger records it as a pass.
  INSERT INTO public.messages (sender_id, recipient_id, content, message_type, metadata)
  VALUES (
    v_uid, v_ask.user_id, left(btrim(coalesce(p_note, '')), 280), 'cardmix',
    jsonb_build_object('media_type', p_item_type, 'media_id', p_item_id, 'media_name', left(btrim(p_item_name), 300), 'media_image', nullif(left(coalesce(p_image_url, ''), 500), ''), 'ask_id', p_ask_id)
  );
  UPDATE public.title_recommendations
     SET ask_id = p_ask_id
   WHERE from_user_id = v_uid AND to_user_id = v_ask.user_id AND item_id = p_item_id AND item_type = p_item_type;
  RETURN 'answered';
END $$;

REVOKE ALL ON FUNCTION public.create_ask(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.answer_ask(bigint, text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_ask(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.answer_ask(bigint, text, text, text, text, text) TO authenticated;

DO $$
BEGIN
  IF to_regclass('public.asks') IS NULL OR to_regprocedure('public.create_ask(text)') IS NULL
     OR to_regprocedure('public.answer_ask(bigint, text, text, text, text, text)') IS NULL OR to_regprocedure('public.are_people(uuid, uuid)') IS NULL THEN
    RAISE EXCEPTION 'ask your people is incomplete';
  END IF;
  RAISE NOTICE 'verified: asks, are_people, create_ask and answer_ask in place';
END $$;

COMMIT;
